//! Generating cloudflared's ingress configuration.
//!
//! **One rule, written once.** Everything under the zone goes to the local
//! proxy, and the proxy decides what it means. The alternative — a rule
//! per service with `originRequest.httpHostHeader` rewriting the Host —
//! would need the file regenerated and cloudflared reloaded every time a
//! worktree appeared, and `httpHostHeader` is a fixed string, so it cannot
//! rewrite per request anyway.
//!
//! What makes the single rule work is that the daemon registers the tunnel
//! hostname in the proxy's routing table alongside the `.localhost` one.
//! The Host header arrives untouched and resolves on the other side.

use std::path::Path;

use crate::{Result, TunnelError, TunnelSettings};

/// The parts of cloudflared's configuration that Minato sets.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct IngressConfig {
    pub tunnel: String,
    /// The hostname pattern that reaches the proxy.
    pub hostname: String,
    /// Where matching requests go.
    pub service: String,
}

impl IngressConfig {
    pub fn from_settings(settings: &TunnelSettings) -> Self {
        Self {
            tunnel: settings.name.clone(),
            // The whole zone, so the file never changes as projects are
            // added — the same shape as the DNS record
            // ([`TunnelSettings::dns_record`]). What actually answers is
            // decided further in: the proxy 404s a hostname it has no
            // route for, so an unclaimed name in the zone reaches nothing.
            hostname: format!("*.{}", settings.domain),
            service: format!("http://127.0.0.1:{}", settings.local_port),
        }
    }
}

/// Renders the configuration file.
///
/// Written by hand rather than through a YAML crate: it is a handful of
/// fixed keys, and the output being predictable matters more than the
/// generality — a user reads this file before trusting it.
pub fn render_config(config: &IngressConfig) -> String {
    format!(
        "# Generated by Minato. Edits are overwritten.\n\
         #\n\
         # Every hostname in the zone reaches the local proxy, which routes\n\
         # on Host. Adding a workspace changes nothing here.\n\
         tunnel: {tunnel}\n\
         \n\
         ingress:\n\
         \x20 - hostname: \"{hostname}\"\n\
         \x20   service: {service}\n\
         \x20 - service: http_status:404\n",
        tunnel = config.tunnel,
        hostname = config.hostname,
        service = config.service,
    )
}

/// Writes the configuration, creating the directory if needed.
pub fn write_config(settings: &TunnelSettings) -> Result<std::path::PathBuf> {
    let path = settings.config_path();
    let contents = render_config(&IngressConfig::from_settings(settings));

    write(&path, &contents)?;
    Ok(path)
}

fn write(path: &Path, contents: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|source| TunnelError::Write {
            path: parent.to_path_buf(),
            source,
        })?;
    }

    std::fs::write(path, contents).map_err(|source| TunnelError::Write {
        path: path.to_path_buf(),
        source,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn settings(dir: &Path) -> TunnelSettings {
        TunnelSettings::new("example.com", dir, 80)
    }

    #[test]
    fn sends_the_whole_zone_to_the_local_proxy() {
        let config = IngressConfig::from_settings(&settings(Path::new("/tmp")));

        assert_eq!(config.hostname, "*.example.com");
        assert_eq!(config.service, "http://127.0.0.1:80");
    }

    #[test]
    fn does_not_rewrite_the_host_header() {
        // The proxy resolves the tunnel hostname itself. Rewriting Host
        // here would send every hostname in the zone to whichever single
        // name the rule named.
        let rendered = render_config(&IngressConfig::from_settings(&settings(Path::new("/tmp"))));

        assert!(!rendered.contains("httpHostHeader"), "got:\n{rendered}");
        assert!(!rendered.contains("originRequest"), "got:\n{rendered}");
    }

    #[test]
    fn falls_through_to_404() {
        // Without a catch-all, cloudflared refuses to start.
        let rendered = render_config(&IngressConfig::from_settings(&settings(Path::new("/tmp"))));
        assert!(rendered.contains("http_status:404"), "got:\n{rendered}");
    }

    #[test]
    fn targets_plain_http_not_the_tls_port() {
        // cloudflared has no reason to trust the local CA, and the hop
        // never leaves loopback.
        let config = IngressConfig::from_settings(&TunnelSettings::new(
            "example.com",
            Path::new("/tmp"),
            8080,
        ));

        assert_eq!(config.service, "http://127.0.0.1:8080");
    }

    #[test]
    fn writes_the_file_and_its_directory() {
        let dir = tempfile::tempdir().expect("tempdir");
        let nested = dir.path().join("tunnel");

        let path = write_config(&settings(&nested)).expect("writes");

        assert_eq!(path, nested.join("config.yml"));
        let contents = std::fs::read_to_string(&path).expect("reads");
        assert!(contents.contains("*.example.com"), "got:\n{contents}");
    }

    #[test]
    fn says_it_is_generated() {
        // A file that overwrites itself has to say so, or an edit is lost
        // without explanation.
        let rendered = render_config(&IngressConfig::from_settings(&settings(Path::new("/tmp"))));
        assert!(
            rendered.starts_with("# Generated by Minato"),
            "got:\n{rendered}"
        );
    }
}
