[package]
name = "kobune-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
indexmap.workspace = true
humantime-serde.workspace = true
humantime.workspace = true
sha2.workspace = true
dirs.workspace = true
chrono.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tracing.workspace = true
