//! What everything needs to know about the LaunchDaemon.
//!
//! The plist itself is generated by the CLI, which is the only side that
//! writes one. What lives here is the part the client and the daemon have
//! to agree on: **whether launchd is managing us**, and how to get it to
//! start the job again.
//!
//! That question decides real behaviour. With a plist installed, launchd
//! holds 80, 443 and 53 whether or not the job is running, so starting a
//! daemon any other way produces one that cannot serve a single URL.

use std::path::{Path, PathBuf};

/// The launchd job name.
pub const LABEL: &str = "dev.kobune.daemon";

/// Where system-wide LaunchDaemons live.
///
/// It has to be `LaunchDaemons`, not per-user `LaunchAgents`: only a
/// launchd running as root can bind a privileged port.
pub const INSTALL_DIR: &str = "/Library/LaunchDaemons";

/// The port whose socket demand-launches the job.
///
/// The plist is always written with the default ports, so this is a
/// constant rather than something to read back out of it.
pub const ACTIVATION_PORT: u16 = 80;

/// The command that hands the socket back to launchd's job.
///
/// **One string, because several places have to say the same thing.** The
/// client names it in the protocol-mismatch error, `doctor` names it as a
/// fix, `setup` names it as a step, and the post-update notice names it as
/// what to run next — all about the same machine state. Spelled out at
/// each site they drift, and a rename leaves some of them advising a
/// command that no longer parses.
///
/// It replaces `kobune daemon stop` plus a `sudo launchctl kickstart` as
/// the *first* answer: stopping alone leaves the machine with no daemon
/// until something happens to reach a port, and the kickstart needs root,
/// which an agent cannot supply. Restarting does both halves and needs
/// neither, because starting reaches for the socket launchd is holding.
///
/// It does not replace [`kickstart_command`] outright. Reaching for the
/// socket only wakes something already listening on it, so where anything
/// else holds :80 the start produces a daemon of its own instead — and
/// forcing the job up from there still takes root. Sites that can be run
/// again after a failure say so as the next step.
pub const RESTART_COMMAND: &str = "kobune daemon restart";

/// Where the installed plist lives.
pub fn plist_path() -> PathBuf {
    Path::new(INSTALL_DIR).join(format!("{LABEL}.plist"))
}

/// Whether the LaunchDaemon has been installed.
///
/// **The file being there is not the same as the job running.** After
/// `kobune daemon stop` the plist stays put while the job is idle, and that
/// combination is exactly the one worth telling apart: it means socket
/// activation can be had back, rather than needing `kobune setup` again.
#[cfg(target_os = "macos")]
pub fn is_installed() -> bool {
    plist_path().is_file()
}

/// Always false where there is no launchd.
#[cfg(not(target_os = "macos"))]
pub fn is_installed() -> bool {
    false
}

/// Whether launchd has the job, rather than only its plist being on disk.
///
/// **The file is not the registration.** A plist copied in by hand, or one
/// whose `bootstrap` was declined, leaves launchd knowing nothing about the
/// job: nothing holds 80, `kickstart` has no service to name, and what is
/// needed is the installation. Once launchd does have it, the opposite
/// holds — a second `bootstrap` of a label it already knows comes back as
/// `Input/output error`, so an installation is the one thing that cannot
/// help.
///
/// Only `print` is asked, which needs no privileges even in the system
/// domain. Being told what state the machine is in should never cost a
/// password.
#[cfg(target_os = "macos")]
pub fn is_loaded() -> bool {
    if !is_installed() {
        return false;
    }

    std::process::Command::new("launchctl")
        .arg("print")
        .arg(format!("system/{LABEL}"))
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .is_ok_and(|status| status.success())
}

/// Always false where there is no launchd.
#[cfg(not(target_os = "macos"))]
pub fn is_loaded() -> bool {
    false
}

/// What launchd has, for the home the caller is asking about.
///
/// **Four states, and each one takes a different step.** Every site that
/// advises anything about launchd is deciding between these, and composing
/// the decision out of [`is_installed`], [`is_loaded`] and the plist at
/// each site is how two of them came to answer one machine differently.
///
/// | State | What helps |
/// | --- | --- |
/// | [`Job::Missing`] | `kobune setup`, which writes the plist |
/// | [`Job::Unregistered`] | `kobune setup`; `kickstart` has no service to name |
/// | [`Job::Registered`] | [`RESTART_COMMAND`], then [`kickstart_command`] |
/// | [`Job::Elsewhere`] | neither: the ports are held for another home |
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Job {
    /// No plist, so launchd was never asked to hold anything.
    Missing,
    /// A plist on disk that launchd does not have — copied in, or with its
    /// `bootstrap` declined.
    Unregistered,
    /// launchd has the job, and it serves this home.
    Registered,
    /// launchd has the job, but its plist names another `KOBUNE_HOME`.
    Elsewhere(PathBuf),
}

/// Which of the four states this machine is in, for `home`.
///
/// The home is asked for rather than resolved here: the answer belongs to
/// the daemon a caller is talking about, and under `KOBUNE_HOME` that is
/// not the same as the one launchd's job serves.
pub fn job(home: &Path) -> Job {
    if !is_installed() {
        return Job::Missing;
    }

    if !is_loaded() {
        return Job::Unregistered;
    }

    match job_elsewhere(home) {
        Some(other) => Job::Elsewhere(other),
        None => Job::Registered,
    }
}

/// The `KOBUNE_HOME` launchd's job serves, when it is not this one.
///
/// **A fourth state.** The plist carries the home it was installed for, and
/// a machine can be running under another one — `KOBUNE_HOME` set for a
/// second instance, or a plist installed from a different account. launchd
/// has a job and holds 80, 443 and 53 for it, and none of that reaches the
/// daemon this process is talking to.
///
/// It is worth its own answer because every command the other three states
/// take is wrong here. `kobune daemon restart` reaches for :80 and gets a
/// daemon serving somewhere else, so it falls back to a direct one;
/// `kickstart` starts that same job again; and `kobune setup` writes a
/// plist for this home whose `bootstrap` launchd answers with `Input/output
/// error`, the label being one it already has. What is left is to point
/// `KOBUNE_HOME` at the home the job serves, or to accept the fallback
/// ports.
///
/// `None` where there is nothing to say: no plist, one for this home, or
/// one from before the home was written into it — an installation that
/// works is not worth inventing a state over.
#[cfg(target_os = "macos")]
fn job_elsewhere(home: &Path) -> Option<PathBuf> {
    let plist = std::fs::read_to_string(plist_path()).ok()?;
    let job = job_home(&plist)?;

    (!same_path(&job, home)).then_some(job)
}

/// Always nothing where there is no launchd.
#[cfg(not(target_os = "macos"))]
fn job_elsewhere(_home: &Path) -> Option<PathBuf> {
    None
}

/// The `KOBUNE_HOME` a plist names.
///
/// The CLI writes it into `EnvironmentVariables`, which is how the job
/// finds its home at all. Read back here rather than in the CLI, because
/// the daemon compares it against its own root as well.
pub fn job_home(plist: &str) -> Option<PathBuf> {
    let (_, rest) = plist.split_once("<key>KOBUNE_HOME</key>")?;
    let (_, value) = rest.split_once("<string>")?;
    let (value, _) = value.split_once("</string>")?;

    let value = unescape_xml(value.trim());
    (!value.is_empty()).then(|| PathBuf::from(value))
}

/// The five entities the plist is written with.
fn unescape_xml(value: &str) -> String {
    value
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"")
        .replace("&apos;", "'")
        // Last: an escaped `&amp;lt;` is the text `&lt;`, not a `<`.
        .replace("&amp;", "&")
}

/// Whether two paths are the same directory.
///
/// Resolved where they exist, since `/tmp` and `/private/tmp` are the same
/// home on macOS and a plist may name either. A path that does not resolve
/// is compared as written — it is still an answer, and the alternative is
/// calling two different homes the same one.
#[cfg(target_os = "macos")]
fn same_path(one: &Path, other: &Path) -> bool {
    let resolved = |path: &Path| std::fs::canonicalize(path).unwrap_or_else(|_| path.to_path_buf());

    resolved(one) == resolved(other)
}

/// The command that starts the job again, for a `fix` or a hint.
///
/// `kickstart` needs root because the job is in the system domain. It is
/// the fallback for when reaching the socket does not wake it — see
/// `kobune-client`, which tries that first precisely so nobody has to run
/// this.
pub fn kickstart_command() -> String {
    format!("sudo launchctl kickstart -k system/{LABEL}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_plist_sits_where_setup_puts_it() {
        assert_eq!(
            plist_path(),
            PathBuf::from("/Library/LaunchDaemons/dev.kobune.daemon.plist")
        );
    }

    #[test]
    fn the_kickstart_command_names_the_system_domain() {
        // A user-domain kickstart would not touch a LaunchDaemon.
        let command = kickstart_command();
        assert!(command.contains("system/dev.kobune.daemon"), "{command}");
        assert!(command.starts_with("sudo "), "{command}");
    }

    #[cfg(not(target_os = "macos"))]
    #[test]
    fn nothing_is_installed_without_launchd() {
        assert!(!is_installed());
        assert!(!is_loaded());
        // There is no launchd to have a job, so the one state that leaves
        // a caller with nothing to run must not be reachable here.
        assert_eq!(job(Path::new("/home/someone/.kobune")), Job::Missing);
    }

    #[cfg(target_os = "macos")]
    #[test]
    fn no_plist_means_launchd_does_not_have_the_job() {
        // The machine running the tests may well have one installed, so
        // this only pins the half that holds either way: without the file
        // there is nothing to have been bootstrapped, and nothing to read
        // a home out of.
        if !is_installed() {
            assert!(!is_loaded());
            assert_eq!(job(Path::new("/Users/someone/.kobune")), Job::Missing);
        }
    }

    #[test]
    fn the_home_comes_out_of_the_environment_block() {
        let plist = "\
  <key>EnvironmentVariables</key>
  <dict>
    <key>KOBUNE_HOME</key>
    <string>/Users/someone/.kobune</string>
  </dict>
";

        assert_eq!(
            job_home(plist),
            Some(PathBuf::from("/Users/someone/.kobune"))
        );
    }

    #[test]
    fn a_plist_from_before_the_home_was_written_names_none() {
        // Left alone deliberately, as with the revision marker: an
        // installation that works is not worth a state of its own.
        assert!(job_home("<key>Label</key>\n<string>dev.kobune.daemon</string>").is_none());
    }

    #[test]
    fn a_home_that_had_to_be_escaped_comes_back_as_it_was_written() {
        // `escape_xml` on the way in, so a directory with an `&` in it
        // would otherwise read as a different home every time.
        let plist = "<key>KOBUNE_HOME</key>\n<string>/Users/a&amp;b/.kobune</string>";

        assert_eq!(job_home(plist), Some(PathBuf::from("/Users/a&b/.kobune")));
    }

    #[cfg(target_os = "macos")]
    #[test]
    fn the_same_home_written_two_ways_is_one_home() {
        // A trailing slash is not a different directory, and neither is a
        // symlinked one — `/tmp` against `/private/tmp` on macOS.
        assert!(same_path(
            Path::new("/Users/someone/.kobune/"),
            Path::new("/Users/someone/.kobune")
        ));
        assert!(!same_path(
            Path::new("/Users/someone/.kobune"),
            Path::new("/Users/someone/.kobune-test")
        ));
    }
}
