[package]
name = "kobune-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
kobune-core.workspace = true
kobune-api.workspace = true
tokio = { workspace = true, features = ["net", "io-util", "time", "process", "rt"] }
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tempfile.workspace = true
