//! What everything needs to know about the LaunchDaemon.
//!
//! The plist itself is generated by the CLI, which is the only side that
//! writes one. What lives here is the part the client and the daemon have
//! to agree on: **whether launchd is managing us**, and how to get it to
//! start the job again.
//!
//! That question decides real behaviour. With a plist installed, launchd
//! holds 80, 443 and 53 whether or not the job is running, so starting a
//! daemon any other way produces one that cannot serve a single URL.

use std::path::{Path, PathBuf};

/// The launchd job name.
pub const LABEL: &str = "dev.minato.daemon";

/// Where system-wide LaunchDaemons live.
///
/// It has to be `LaunchDaemons`, not per-user `LaunchAgents`: only a
/// launchd running as root can bind a privileged port.
pub const INSTALL_DIR: &str = "/Library/LaunchDaemons";

/// The port whose socket demand-launches the job.
///
/// The plist is always written with the default ports, so this is a
/// constant rather than something to read back out of it.
pub const ACTIVATION_PORT: u16 = 80;

/// The command that hands the socket back to launchd's job.
///
/// **One string, because several places have to say the same thing.** The
/// client names it in the protocol-mismatch error, `doctor` names it as a
/// fix, `setup` names it as a step, and the post-update notice names it as
/// what to run next — all about the same machine state. Spelled out at
/// each site they drift, and a rename leaves some of them advising a
/// command that no longer parses.
///
/// It replaces `minato daemon stop` plus a `sudo launchctl kickstart` as
/// the *first* answer: stopping alone leaves the machine with no daemon
/// until something happens to reach a port, and the kickstart needs root,
/// which an agent cannot supply. Restarting does both halves and needs
/// neither, because starting reaches for the socket launchd is holding.
///
/// It does not replace [`kickstart_command`] outright. Reaching for the
/// socket only wakes something already listening on it, so where anything
/// else holds :80 the start produces a daemon of its own instead — and
/// forcing the job up from there still takes root. Sites that can be run
/// again after a failure say so as the next step.
pub const RESTART_COMMAND: &str = "minato daemon restart";

/// Where the installed plist lives.
pub fn plist_path() -> PathBuf {
    Path::new(INSTALL_DIR).join(format!("{LABEL}.plist"))
}

/// Whether the LaunchDaemon has been installed.
///
/// **The file being there is not the same as the job running.** After
/// `minato daemon stop` the plist stays put while the job is idle, and that
/// combination is exactly the one worth telling apart: it means socket
/// activation can be had back, rather than needing `minato setup` again.
#[cfg(target_os = "macos")]
pub fn is_installed() -> bool {
    plist_path().is_file()
}

/// Always false where there is no launchd.
#[cfg(not(target_os = "macos"))]
pub fn is_installed() -> bool {
    false
}

/// Whether launchd has the job, rather than only its plist being on disk.
///
/// **The file is not the registration.** A plist copied in by hand, or one
/// whose `bootstrap` was declined, leaves launchd knowing nothing about the
/// job: nothing holds 80, `kickstart` has no service to name, and what is
/// needed is the installation. Once launchd does have it, the opposite
/// holds — a second `bootstrap` of a label it already knows comes back as
/// `Input/output error`, so an installation is the one thing that cannot
/// help.
///
/// Only `print` is asked, which needs no privileges even in the system
/// domain. Being told what state the machine is in should never cost a
/// password.
#[cfg(target_os = "macos")]
pub fn is_loaded() -> bool {
    print_job().is_some()
}

/// Always false where there is no launchd.
#[cfg(not(target_os = "macos"))]
pub fn is_loaded() -> bool {
    false
}

/// Whether launchd's job is running, rather than only registered.
///
/// **Three states, not two.** [`is_installed`] is the plist on disk,
/// [`is_loaded`] is launchd knowing the job, and this is something actually
/// behind the sockets. After `minato daemon stop` the middle one still
/// holds while nothing answers, which is the state [`RESTART_COMMAND`]
/// exists to leave.
///
/// It is what tells a wake that worked from one that did not.
/// `minato daemon restart` exits 0 either way — a daemon started directly,
/// outside launchd, is still a daemon — so its exit status cannot answer
/// this and asking launchd is the only thing that can.
///
/// `launchctl print` names a `pid` only while the job has one. Asking needs
/// no privileges; being told the state should never cost a password.
#[cfg(target_os = "macos")]
pub fn is_running() -> bool {
    print_job().is_some_and(|job| names_a_pid(&job))
}

/// Always false where there is no launchd.
#[cfg(not(target_os = "macos"))]
pub fn is_running() -> bool {
    false
}

/// What launchd has to say about the job, or nothing where it has no job.
///
/// **One place runs `launchctl print`.** [`is_loaded`] and [`is_running`]
/// are two readings of the same answer, and asking twice spawns the same
/// process to be told the same thing — or, across the gap between the two
/// calls, something else.
#[cfg(target_os = "macos")]
fn print_job() -> Option<String> {
    if !is_installed() {
        return None;
    }

    let output = std::process::Command::new("launchctl")
        .arg("print")
        .arg(format!("system/{LABEL}"))
        .stderr(std::process::Stdio::null())
        .output()
        .ok()?;

    output
        .status
        .success()
        .then(|| String::from_utf8_lossy(&output.stdout).into_owned())
}

/// Whether that output names a running process.
///
/// **Split out because it is the half that can be tested** — the rest is
/// `launchctl` itself, which no CI runner has a job for. `launchctl` leaves
/// the line out entirely rather than naming an absent pid, so the property
/// is a `pid` key with a number after it, read loosely enough to survive
/// the spacing changing: reading it wrong the other way says a wake landed
/// when it did not, and writes `/etc/resolver/localhost` for a port nothing
/// is listening on.
#[cfg(target_os = "macos")]
fn names_a_pid(job: &str) -> bool {
    job.lines().any(|line| {
        line.trim()
            .strip_prefix("pid")
            .and_then(|rest| rest.trim_start().strip_prefix('='))
            .is_some_and(|value| value.trim().parse::<u32>().is_ok())
    })
}

/// The command that starts the job again, for a `fix` or a hint.
///
/// `kickstart` needs root because the job is in the system domain. It is
/// the fallback for when reaching the socket does not wake it — see
/// `minato-client`, which tries that first precisely so nobody has to run
/// this.
pub fn kickstart_command() -> String {
    format!("sudo launchctl kickstart -k system/{LABEL}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_plist_sits_where_setup_puts_it() {
        assert_eq!(
            plist_path(),
            PathBuf::from("/Library/LaunchDaemons/dev.minato.daemon.plist")
        );
    }

    #[test]
    fn the_kickstart_command_names_the_system_domain() {
        // A user-domain kickstart would not touch a LaunchDaemon.
        let command = kickstart_command();
        assert!(command.contains("system/dev.minato.daemon"), "{command}");
        assert!(command.starts_with("sudo "), "{command}");
    }

    #[cfg(not(target_os = "macos"))]
    #[test]
    fn nothing_is_installed_without_launchd() {
        assert!(!is_installed());
        assert!(!is_loaded());
        // The third state is a state too. `setup` reads it to decide
        // whether the resolver names :53, so a stub that ever answered
        // otherwise would have it write one for a port nothing holds.
        assert!(!is_running());
    }

    #[cfg(target_os = "macos")]
    #[test]
    fn no_plist_means_launchd_does_not_have_the_job() {
        // The machine running the tests may well have one installed, so
        // this only pins the half that holds either way: without the file
        // there is nothing to have been bootstrapped, and nothing
        // bootstrapped is nothing running.
        if !is_installed() {
            assert!(!is_loaded());
            assert!(!is_running());
        }
    }

    #[cfg(target_os = "macos")]
    #[test]
    fn a_job_with_a_pid_is_running() {
        // Trimmed from `launchctl print system/dev.minato.daemon`.
        let job = "\tstate = running\n\tpid = 4821\n\tprogram = /usr/local/bin/minato-daemon\n";

        assert!(names_a_pid(job));
    }

    #[cfg(target_os = "macos")]
    #[test]
    fn a_registered_job_with_no_pid_is_not_running() {
        // What launchd prints for the job `minato daemon stop` left: it
        // still has it, and the pid line is simply absent.
        let job = "\tstate = not running\n\tprogram = /usr/local/bin/minato-daemon\n";

        assert!(!names_a_pid(job));
    }

    #[cfg(target_os = "macos")]
    #[test]
    fn the_pid_is_read_loosely_enough_to_survive_the_spacing() {
        // The output is `launchctl`'s to format, and a false negative here
        // is the same failure as a false positive, from the other side.
        assert!(names_a_pid("  pid   =   4821"));
        assert!(names_a_pid("pid=4821"));

        // Not every key that starts with those three letters.
        assert!(!names_a_pid("\tpidfile = /var/run/minato.pid"));
        assert!(!names_a_pid("\tpid = (none)"));
    }
}
