//! What everything needs to know about the LaunchDaemon.
//!
//! The plist itself is generated by the CLI, which is the only side that
//! writes one. What lives here is the part the client and the daemon have
//! to agree on: **whether launchd is managing us**, and how to get it to
//! start the job again.
//!
//! That question decides real behaviour. With a plist installed, launchd
//! holds 80, 443 and 53 whether or not the job is running, so starting a
//! daemon any other way produces one that cannot serve a single URL.

use std::path::{Path, PathBuf};

/// The launchd job name.
pub const LABEL: &str = "dev.minato.daemon";

/// Where system-wide LaunchDaemons live.
///
/// It has to be `LaunchDaemons`, not per-user `LaunchAgents`: only a
/// launchd running as root can bind a privileged port.
pub const INSTALL_DIR: &str = "/Library/LaunchDaemons";

/// The port whose socket demand-launches the job.
///
/// The plist is always written with the default ports, so this is a
/// constant rather than something to read back out of it.
pub const ACTIVATION_PORT: u16 = 80;

/// Where the installed plist lives.
pub fn plist_path() -> PathBuf {
    Path::new(INSTALL_DIR).join(format!("{LABEL}.plist"))
}

/// Whether the LaunchDaemon has been installed.
///
/// **The file being there is not the same as the job running.** After
/// `minato daemon stop` the plist stays put while the job is idle, and that
/// combination is exactly the one worth telling apart: it means socket
/// activation can be had back, rather than needing `minato setup` again.
#[cfg(target_os = "macos")]
pub fn is_installed() -> bool {
    plist_path().is_file()
}

/// Always false where there is no launchd.
#[cfg(not(target_os = "macos"))]
pub fn is_installed() -> bool {
    false
}

/// The command that starts the job again, for a `fix` or a hint.
///
/// `kickstart` needs root because the job is in the system domain. It is
/// the fallback for when reaching the socket does not wake it — see
/// `minato-client`, which tries that first precisely so nobody has to run
/// this.
pub fn kickstart_command() -> String {
    format!("sudo launchctl kickstart -k system/{LABEL}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_plist_sits_where_setup_puts_it() {
        assert_eq!(
            plist_path(),
            PathBuf::from("/Library/LaunchDaemons/dev.minato.daemon.plist")
        );
    }

    #[test]
    fn the_kickstart_command_names_the_system_domain() {
        // A user-domain kickstart would not touch a LaunchDaemon.
        let command = kickstart_command();
        assert!(command.contains("system/dev.minato.daemon"), "{command}");
        assert!(command.starts_with("sudo "), "{command}");
    }

    #[cfg(not(target_os = "macos"))]
    #[test]
    fn nothing_is_installed_without_launchd() {
        assert!(!is_installed());
    }
}
